//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://i.imgur.com/eE29vX4.png
        ///http://i.imgur.com/xX2AeDR.png
        ///http://i.imgur.com/hBFRUuW.png
        ///http://i.imgur.com/WDWK4nF.png
        ///http://i.imgur.com/zxtD5Zw.png
        ///http://i.imgur.com/MrkAGKR.png
        ///http://i.imgur.com/o3Nyw4R.png
        ///http://i.imgur.com/SzP5370.png
        ///http://i.imgur.com/oHaP6I3.png
        ///http://i.imgur.com/kSU7Zca.png
        ///http://i.imgur.com/SAJJ1oH.png
        ///http://i.imgur.com/BYvRbs8.png
        ///http://i.imgur.com/VzFTsGg.png
        ///http://i.imgur.com/qigJZWa.png
        ///http://i.imgur.com/gskym.png
        ///.
        /// </summary>
        public static string Labrador {
            get {
                return ResourceManager.GetString("Labrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://i.imgur.com/ozJD7SC.png
        ///http://i.imgur.com/E5vBM5Z.png
        ///http://i.imgur.com/miiP4NI.png
        ///http://i.imgur.com/GCE8dj5.png
        ///http://i.imgur.com/NGG3Yir.png
        ///http://i.imgur.com/q53cfRy.png
        ///http://i.imgur.com/Flic3TB.png
        ///http://i.imgur.com/zjgtrf9.png
        ///http://i.imgur.com/Mda3xXr.png
        ///http://i.imgur.com/IOh5mgB.png
        ///http://i.imgur.com/Fl2ivvG.png
        ///http://i.imgur.com/iLzWvSY.png
        ///http://i.imgur.com/RQKBN3F.png
        ///http://i.imgur.com/8c3RpI0.png
        ///http://i.imgur.com/7ysJzS4.png
        ///http://i.imgur.com/uccGfLn.png
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Pug {
            get {
                return ResourceManager.GetString("Pug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://i.imgur.com/wR38uBx.png
        ///http://i.imgur.com/CHRlo0W.png
        ///http://i.imgur.com/tXnch1O.png
        ///http://i.imgur.com/VCgfaB2.png
        ///http://i.imgur.com/Ror46i4.png
        ///http://i.imgur.com/Ful5PwH.png
        ///http://i.imgur.com/C4rrJdn.png
        ///http://i.imgur.com/Ao9bR9A.png
        ///http://i.imgur.com/R14AU0I.png
        ///http://i.imgur.com/gpH8wIV.png
        ///http://i.imgur.com/luPxoig.png
        ///http://i.imgur.com/MiIDyfD.png
        ///http://i.imgur.com/4qmmRFj.png
        ///http://i.imgur.com/ZSzHQ2q.png
        ///http://i.imgur.com/PoA6rLg.png
        ///http://i.imgur.com/NYwynk3.png
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Retriever {
            get {
                return ResourceManager.GetString("Retriever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://i.imgur.com/oSieVUO.png
        ///http://i.imgur.com/qtXIL.png
        ///http://i.imgur.com/qWLKy8a.jpg
        ///.
        /// </summary>
        public static string Yorkie {
            get {
                return ResourceManager.GetString("Yorkie", resourceCulture);
            }
        }
    }
}
